### ISSUE TITLE
About the use of random seed in assignment 5

### ISSUE THREAD

**Issue by KaiChen1998** [xixiaoyao/CS224n-winter-together#31]
一个很奇怪的事情是，为什么尽管并没有改变随机种子，A5中每一次从头开始训练都会收敛到不同的结果，讲道理当你对于torch、numpy和random都设好了相同的随机种子之后的答案应该是不变的才对啊，希望有大佬可以解答

**Comment by xixiaoyao** [comment]
这个是正常的。cudnn的运算是有随机性的，哪怕种子都固定了，经过若干训练steps的累积，也容易收敛到不同到结果。网上也有一些尝试固定cudnn种子的做法，比如pytorch中
```
torch.cuda.manual_seed_all(SEED)
torch.backends.cudnn.deterministic=True
```
你可以尝试一下，我没试过。一般来说大家还是习惯于多次训练取个平均值

**Comment by KaiChen1998** [comment]
@xixiaoyao 嗯发现了是cudnn的随机性问题，实测这个case中加入这条就可以得到确定的满分答案
```
torch.backends.cudnn.deterministic=True
```

Reference: https://github.com/pytorch/pytorch/issues/7068#issuecomment-487907668

**Comment by xixiaoyao** [comment]
好的，赞~
